services:
  horizonxl:
    build:
      context: .
      dockerfile: Dockerfile
    image: horizonxl-local
    container_name: horizonxl
    env_file:
      - .env
    environment:
      FLASK_DEBUG: "False"
      FLASK_HOST: "0.0.0.0"
      PORT: "5001"
    ports:
      - "80:5001"
    restart: unless-stopped
    volumes:
      - ./backend/uploads:/app/backend/uploads
